# Autogenerated wrapper script for PIOLib_jll for aarch64-linux-musl
export libpio

JLLWrappers.@generate_wrapper_header("PIOLib")
JLLWrappers.@declare_library_product(libpio, "libpio.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpio,
        "lib/libpio.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
